
import { Article } from '../types';

const article: Article = {
  id: "events-weekly",
  title: "What’s On · Events Calendar",
  author: "Listings Desk",
  date: "2025-08-27",
  category: "Events",
  excerpt: "Your complete guide to events in Bad Belzig and the Hoher Fläming for August, September and October 2025, now with an improved layout.",
  hero: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=2070",
  body: [
    "Here is your comprehensive guide to what's happening in and around Bad Belzig for the upcoming months. From recurring weekly activities to special one-off events, there's something for everyone. Event details are subject to change, so please contact organisers to confirm arrangements before attending.",
    "**RECURRING EVENTS**",
    "Every Sunday::11:00 AM::Stadt- und Burgführung::Tourist-Information, Marktplatz 1::A guided tour of the town and castle.::Tel. 033841/94900::Tour",
    "Every Sunday until Sep 28::3:00 PM::ZEGG Sonntagsführung::ZEGG, Rosa-Luxemburg-Straße 89::A tour with space for conversation and questions.::Tel. 033841/595100::Tour",
    "Every Monday & Wednesday::Varies::Xtra-Film::Hofgartenkino Belzig::Enjoy a weekly rotating program of art-house films. Check weekly schedule for times.::Tel. 033841/380888::Film",
    "Every Monday & Friday::8:30 - 11:00 AM::Alphabetisierungswerkstatt::Hans-Marchwitza-Straße 1::German for beginners (except holidays).::Tel. 033203/ 803710::Community",
    "Every Tuesday::9:00 AM - 3:00 PM::Sprechtag Existenzgründung::Niemegker Straße 35::Free consultation for business founders. Appointments required.::Tel. 033841/65152::Community",
    "Every Tuesday::from 4:00 PM::Besichtigung des Eisenbahnmuseums::Railway Museum::Railway Museum visit. Appointment required.::Tel. 0160/ 97459602::Museum",
    "Every Wednesday & Friday::9:00 AM & 1:00 PM::Offener Lernraum::Klinke 1, Hans-Marchwitza-Str.1::Open learning space for adults for reading, writing, math, and computer skills.::Tel. 0163/ 0800 759::Community",
    "Wed-Fri & Sat-Sun::Varies::Ausstellung 'Die Zinnfigur'::Heimatmuseum auf der Burg Eisenhardt::Exhibition: 'The Tin Figure - a means of representing local history.' (Wed-Fri: 12-5 PM, Sat-Sun: 11-5 PM)::Tel. 033841/ 42461::Art",
    "Every Saturday & Sunday::9:30 AM::Reiterhoftag::Reiter- & Erlebnisbauernhof, Groß Briesen::A day at the horse farm for all skill levels.::Tel. 033846/41673::Family",
    "Saturday & Sunday until Oct 12::12:00 PM - 5:00 PM::Susanne Kraißer – Bronzeplastiken::Kunstverein Hoher Fläming, Burg Eisenhardt::Exhibition of bronze sculptures.::Tel. 0175/ 8213961::Art",
    "**AUGUST 2025 EVENTS**",
    "FRI, 22 AUG::1:00 PM - 4:00 PM::Wanderung mit dem Bürgermeister::Rathaus, Wiesenburger Straße 6::Hike with the Mayor.::Herr Gottschalk, Tel. 033841/ 32691::Community",
    "FRI, 22 AUG::7:30 PM::Live-Musik im KURPARK15::Restaurant KURPARK15, SteinTherme::Live music with Carlos' Groove Kitchen. Table reservations recommended.::Tel. 033841/388077::Music",
    "SAT, 23 AUG - SUN, 31 AUG::All Day::62. Burgfestwoche::Innenstadt Bad Belzig::62nd Castle Festival Week with traditional cultural and sporting events.::www.altstadtsommer.com::Festival",
    "SAT, 23 AUG::11:00 AM - 6:00 PM::9. Kunstbummel Bad Belzig::Innenstadt Bad Belzig::9th Bad Belzig Art Stroll with open studios, galleries, museums and live music at 12 stations.::www.kunstbummel-bad-belzig.de::Art",
    "SAT, 23 AUG::7:00 PM::Sommertheater & Eröffnung der Burgfestwoche::Naturbühne der Burg Eisenhardt::Summer theatre and opening of the 62nd Castle Festival Week.::Tel. 033841/ 94900::Culture",
    "SUN, 24 AUG::10:00 AM - 6:00 PM::Besichtigung Bockwindmühle Borne::Borne Post Mill::Guided tours of the historic Borne post mill. Price €2.00 p.p.::Müllerin Hänsch-Goldau, Tel. 0179/ 7577809::History",
    "FRI, 29 AUG - SUN, 31 AUG::All Day::23. Bad Belziger Altstadtsommer::Innenstadt Bad Belzig::23rd Bad Belzig Old Town Summer. Art and culture in the historic courtyards.::::Festival",
    "FRI, 29 AUG::6:00 PM::Das 11. Komische Festival – Frauentag::KleinKunstWerk Bad Belzig::11th 'Belziger Bachstelze' Comedy Festival - Women's Day.::Tel. 033841/ 796981::Culture",
    "FRI, 29 AUG::7:00 PM::Lampionumzug::Altstadt, Ecke Töpferstraße/Mauerstraße::Lantern parade through the town moat to Burg Eisenhardt.::::Family",
    "SAT, 30 AUG::6:00 PM::Das 11. Komische Festival – Herrentag::KleinKunstWerk Bad Belzig::11th 'Belziger Bachstelze' Comedy Festival - Men's Day.::Tel. 033841/ 796981::Culture",
    "SUN, 31 AUG::11:00 AM - 3:00 PM::Paulinenhof Brunch::Paulinenhof, Kuhlowitz::Enjoy a Sunday brunch buffet.::Tel. 033841/4408-0::Food",
    "**SEPTEMBER 2025 EVENTS**",
    "MON, 01 SEP::3:00 PM::'Grüne Runde' - Städtisches Gärtnern::Klinke 1, Hans-Marchwitza-Straße 1::Urban gardening session.::::Community",
    "MON, 01 SEP::4:30 PM::Gedenkspaziergang::Gedenkstein Grüner Grund::A 6km commemorative walk on the history of the Roederhof women's concentration camp subcamp.::Tel.: 033841/8240::History",
    "FRI, 05 SEP::7:30 PM::Dr. Büchners Tatort Belzig::Tourist-Information::A theatrical city walk through the criminal episodes of Bad Belzig's past.::Tel. 033841/94900::Tour",
    "SAT, 06 SEP::10:00 AM::Finissage der Aktion KunstSchauFenster::Marktplatz::Final tour of the open-air gallery in the old town.::::Art",
    "SAT, 06 SEP::12:00 PM - 3:00 PM::ABC-Schützen Lunch::Paulinenhof, Kuhlowitz::A festive lunch to celebrate school enrolment.::Tel. 033841/4408-0::Food",
    "SAT, 13 SEP & SUN, 14 SEP::11:00 AM - 6:00 PM::Flämingmarkt mit Kreiserntefest::Handwerkerhof, Görzke::Regional market with harvest festival activities.::Tel. 033849/ 901948::Market",
    "SAT, 20 SEP::10:00 AM - 2:00 PM::Familientag in der SteinTherme::SteinTherme::Fun and games for the whole family with a 20% discount on admission.::Tel. 033841/38800::Family",
    "SUN, 21 SEP::4:00 PM::Vortrag über die Technik des Bronzegusses::Kunstverein Hoher Fläming, Burg Eisenhardt::Lecture on bronze casting techniques by Susanne Kraißer, followed by a concert.::::Art",
    "FRI, 26 SEP::3:00 PM - 6:00 PM::10 Jahre Paulinenhof – Tag der offenen Tür::Paulinenhof, Kuhlowitz::Open house to celebrate the 10th anniversary of Paulinenhof.::Tel. 033841/4408-0::Community",
    "SAT, 27 SEP::6:00 PM - 11:00 PM::Bayrischer Abend::Paulinenhof, Kuhlowitz::A Bavarian evening celebration. Dirndl & Lederhosen encouraged!::Tel. 033841/4408-0::Food",
    "SUN, 28 SEP::11:00 AM - 2:00 PM::Herbst-Brunch im KURPARK15::Restaurant KURPARK15, SteinTherme::Autumn brunch. Reservations recommended.::Tel. 033841/388077::Food",
    "**OCTOBER 2025 EVENTS**",
    "SAT, 04 OCT::3:00 PM::Kleines Orgelkonzert::Bricciuskirche::A small organ concert at Briccius Church.::Tel. 033841/ 94900::Music",
    "SUN, 05 OCT::12:00 PM - 6:00 PM::Schmerwitzer Erntedankfest::Gut Schmerwitz::Thanksgiving festival with music, children's activities, and grilled food.::Tel. 033849/9080::Festival",
    "SAT, 11 OCT::10:00 AM - 2:00 PM::Familientag SteinTherme::SteinTherme::Fairytales, a magic carpet, and culinary surprises for the kids.::Tel. 033841/ 388 00::Family",
    "SUN, 12 OCT::from 7:45 AM::47. Burgenlauf::Burg Eisenhardt::Annual castle run with distances from 1.2km to a 50km ultra marathon.::www.burgenlauf.de::Sport",
    "FRI, 17 OCT::6:30 PM - 1:00 AM::Mondscheinsauna: Nacht der Elemente::SteinTherme::Experience the elements of light, water, fire, and earth with special sauna infusions and extended hours. No extra charge.::Tel. 033841/ 388 00::Wellness",
    "THU, 23 OCT::2:00 PM - 5:00 PM::Herbstfest::Albert-Baur-Halle::Autumn festival with coffee, music, and dancing.::Herr Gottschalk, Tel. 033841/ 32691::Festival",
    "SAT, 25 OCT::from 1:00 PM::'Feuer und Flamme für unsere Museen'::Museums in Potsdam-Mittelmark::'Fire and Flame for our Museums' event.::www.Potsdam-Mittelmark.de::Museum",
    "THU, 30 OCT::5:00 PM - 10:00 PM::15. Kürbisnacht::Innenstadt::15th annual Pumpkin Night with late-night shopping and more.::Tel. 033841/ 94900::Festival",
    "FRI, 31 OCT::6:00 PM - 10:00 PM::Halloween-Sauna::SteinTherme::Experience infusions from the world of darkness with a special schedule and spooky extras.::Tel. 033841/ 388 00::Wellness"
  ],
};

export default article;
